---
- name: Join worker
  shell: "kubeadm join 192.168.56.7:6443 --token {{ hostvars['DUMMY_HOST']['TOKEN'] }} --discovery-token-ca-cert-hash sha256:{{ hostvars['DUMMY_HOST']['CERT'] }}"
  register: token
