---
- name: Add an Apt signing key, uses whichever key is at the URL
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add docker repo
  shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install Docker
  apt: 
    name: "{{ pkg_list }}"
    state: present
    update_cache: true

- name: Adding existing user '{{ user }}' to group docker
  user: 
    name: '{{ user }}'
    groups: ['docker',]
    append: yes

- name: Setting up daemon.json
  shell: |
    cat <<EOF | tee /etc/docker/daemon.json
    {
      "exec-opts": ["native.cgroupdriver=systemd"],
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "100m"
      },
      "storage-driver": "overlay2"
    }
    EOF

- name: Create systemd docker folder
  shell: mkdir -p /etc/systemd/system/docker.service.d

- name: Reload services
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker